version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sso_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:8443"
      - "8080:8080"
      - "80:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTPS_CLIENT_AUTH=required
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/sso_db
      - KC_DB_PASSWORD=postgres
      - KC_DB_USERNAME=postgres
      - KC_LOG_CONSOLE_COLOR=true
      - KC_DIR=/etc/keycloak/exports
      - KC_HTTPS_PROTOCOLS=TLSv1.3,TLSv1.2
      - KC_HOSTNAME=44.210.91.80:8080
      - KC_HTTP_PORT=8080
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
      - KC_PROXY=edge
      - KC_FEATURES=token-exchange,admin-fine-grained-authz
      - PROXY_ADDRESS_FORWARDING=true
      - KC_HOSTNAME_STRICT_BACKCHANNEL=true
    command: ["start", "--optimized"]
    volumes:
      - $PWD/kcdata/:/etc/keycloak/
