version: '3.8'

services:
  keycloak:
    image: keycloak-custom:1.0.0
    ports:
      - "8443:8443"
      - "8090:8090"
    networks:
      - keycloak_pg_net
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTPS_CLIENT_AUTH: required
      KC_DB: postgres
      KC_DB_URL: ${DB_URL:-db_url}
      KC_DB_PASSWORD: ${DB_PASSWORD:-db_pass}
      KC_DB_USERNAME: ${DB_USER:-db_user}
      KC_HOSTNAME_STRICT: 'false'
      KC_LOG_CONSOLE_COLOR: 'true'
      KC_DIR: /etc/keycloak/exports
      KC_HTTP_ENABLED: 'true'
      KC_HTTP_PORT: '8090'
      KC_PROXY_HEADERS: 'xforwarded'
    command: ["start", "--optimized"]
    volumes:
      - ./kcdata/:/etc/keycloak/

networks:
  keycloak_pg_net:
    driver: 
      bridge